AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  # -------- DYNAMODB-TABLES --------
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: inkboard-notes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # -------- LAMBDAS --------

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/health/healthHandler.handler
      Runtime: nodejs22.x

      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/health/healthHandler.ts

  CreateNoteApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/createNoteHandler.createNoteHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /notes
            Method: post

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/createNoteHandler.ts

  GetNoteByIdApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/getNoteByIdHandler.getNoteByIdHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/getNoteByIdHandler.ts

  GetAllNotesApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/getAllNotesHandler.getAllNotesHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /notes
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/getAllNotesHandler.ts
