AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/health/healthHandler.handler
      Runtime: nodejs22.x

      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/health/healthHandler.ts
