AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/health/healthHandler.handler
      Runtime: nodejs22.x

      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/health/healthHandler.ts

  CreateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/createNoteHandler.createNoteHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        CreateNoteApi:
          Type: Api
          Properties:
            Path: /notes
            Method: post

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/createNoteHandler.ts

  GetNoteByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/getNoteByIdHandler.getNoteByIdHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        GetNoteByIdApi:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/getNoteByIdHandler.ts

  GetAllNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/getAllNotesHandler.getAllNotesHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        GetAllNotesApi:
          Type: Api
          Properties:
            Path: /notes
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/getAllNotesHandler.ts

  UpdateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/updateNoteHandler.updateNoteHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        CreateNoteApi:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: patch

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/updateNoteHandler.ts

  DeleteNoteByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../apps/api
      Handler: src/features/notes/handlers/deleteNoteByIdHandler.deleteNoteByIdHandler
      Runtime: nodejs22.x

      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

      Events:
        DeleteNoteByIdApi:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: delete

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/features/notes/handlers/deleteNoteByIdHandler.ts

  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: inkboard-notes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
